TABLE_UTILISATEUR = "utilisateur"
TABLE_CLIENT = "client"
TABLE_REUNION = "reunion"
TABLE_ATTESTATION = "attestation_organisateur"
TABLE_CONSENTEMENT_PARTICIPANT = "consentement_participant"
TABLE_LOCUTEUR = "locuteur"
TABLE_SEGMENT = "segment"
TABLE_COMPTE_RENDU = "compte_rendu"
TABLE_POINT_CLE = "point_cle"
TABLE_DECISION = "decision"
TABLE_ACTION = "action"
TABLE_THEME = "theme"
TABLE_REUNION_THEME = "reunion_theme"

MODE_DICTAPHONE = "dictaphone"
BASE_LEGALE_CONSENTEMENT = "consentement"
VERSION_ATTESTATION = "v1"

STATUT_EN_ATTENTE = "en_attente"
STATUT_TRANSCRIPTION = "transcription"
STATUT_ANALYSE = "analyse"
STATUT_TERMINE = "termine"
STATUT_ERREUR = "erreur"
STATUT_ATTESTATION_MANQUANTE = "attestation_manquante"
